name: try bitnami-git
on: [push]
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    container:
      image: bitnami/git:2
      volumes:
        - /usr/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - run: task --help

